export const HOMEPAGE_DATA = [
    {
        homepageId:0,
        homepageLogo:'http://oj51kbaw5.bkt.clouddn.com/jianshu.svg',
        homepageUrl:''
    },
    {
        homepageId:1,
        homepageLogo:'http://oj51kbaw5.bkt.clouddn.com/behance.svg',
        homepageUrl:''
    },
    {
        homepageId:2,
        homepageLogo:'http://oj51kbaw5.bkt.clouddn.com/dribbble.svg',
        homepageUrl:''
    },
    {
        homepageId:3,
        homepageLogo:'http://oj51kbaw5.bkt.clouddn.com/15yan.svg',
        homepageUrl:''
    },
    {
        homepageId:4,
        homepageLogo:'http://oj51kbaw5.bkt.clouddn.com/500px.svg',
        homepageUrl:''
    },
    {
        homepageId:5,
        homepageLogo:'http://oj51kbaw5.bkt.clouddn.com/next.svg',
        homepageUrl:''
    },
    {
        homepageId:6,
        homepageLogo:'http://oj51kbaw5.bkt.clouddn.com/googlephoto.svg',
        homepageUrl:''
    },
    {
        homepageId:7,
        homepageLogo:'http://oj51kbaw5.bkt.clouddn.com/tumblr.svg',
        homepageUrl:''
    },
    {
        homepageId:8,
        homepageLogo:'http://oj51kbaw5.bkt.clouddn.com/linkedin.svg',
        homepageUrl:''
    },
    {
        homepageId:9,
        homepageLogo:'http://oj51kbaw5.bkt.clouddn.com/viso.svg',
        homepageUrl:''
    },
    {
        homepageId:10,
        homepageLogo:'http://oj51kbaw5.bkt.clouddn.com/ui.svg',
        homepageUrl:''
    },
    {
        homepageId:11,
        homepageLogo:'http://oj51kbaw5.bkt.clouddn.com/media.svg',
        homepageUrl:''
    },
    {
        homepageId:12,
        homepageLogo:'http://oj51kbaw5.bkt.clouddn.com/facebook.svg',
        homepageUrl:''
    },
    {
        homepageId:13,
        homepageLogo:'http://oj51kbaw5.bkt.clouddn.com/ins.svg',
        homepageUrl:''
    },
    {
        homepageId:14,
        homepageLogo:'http://oj51kbaw5.bkt.clouddn.com/wechat.svg',
        homepageUrl:''
    },
    {
        homepageId:15,
        homepageLogo:'http://oj51kbaw5.bkt.clouddn.com/zhihu.svg',
        homepageUrl:''
    },
    {
        homepageId:16,
        homepageLogo:'http://oj51kbaw5.bkt.clouddn.com/weibo.svg',
        homepageUrl:''
    },
    {
        homepageId:17,
        homepageLogo:'http://oj51kbaw5.bkt.clouddn.com/yotubo.svg',
        homepageUrl:''
    }
];